/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface FileToSend {
  fileId: string
  filePath: string
  fileName: string
  fileType: string
  size: number
}

export interface ProgressInfo {
  sessionId: string
  fileId: string
  bytesSent: number
  totalBytes: number
}

export interface SendResult {
  sessionId: string
  success: boolean
  failedFiles: Array<string>
}

export interface ServerConfig {
  alias: string
  deviceModel: string
  deviceType: string
  port: number
  saveDir: string
  useHttps: boolean
}

export interface ServerHandle {
  fingerprint: string
  port: number
}

export interface ServerStatus {
  running: boolean
  activeSession?: string
  fingerprint?: string
}

export interface ShareLinkInfo {
  url: string
  port: number
  sessionId: string
}

export interface TargetDevice {
  ip: string
  port: number
  fingerprint: string
  protocol: string
}

export interface TransferFileInfo {
  fileId: string
  fileName: string
  size: number
  fileType: string
}

export interface TransferRequest {
  sessionId: string
  senderAlias: string
  senderFingerprint: string
  files: Array<TransferFileInfo>
}

export declare function computeFingerprint(certPem: string): string

export declare function createServer(config: ServerConfig): Promise<ServerHandle>

export declare function createShareLink(files: Array<FileToSend>, alias: string): Promise<ShareLinkInfo>

export declare function getServerStatus(): ServerStatus

export declare function pollPendingRequests(): Array<TransferRequest>

export declare function pollProgress(): Array<ProgressInfo>

export declare function pollSendProgress(): Array<ProgressInfo>

export declare function pollShareProgress(): Array<ProgressInfo>

export declare function respondTransfer(sessionId: string, accept: boolean): Promise<void>

export declare function sendFiles(target: TargetDevice, senderAlias: string, files: Array<FileToSend>): Promise<SendResult>

export declare function stopServer(): Promise<void>

export declare function stopShareServer(): Promise<void>

export declare function verifyFingerprint(certPem: string, expected: string): boolean

