/* auto-generated by OHOS-RS */
/* eslint-disable */



export interface FileMetadataResult {
  lastModified?: string
  lastAccessed?: string
}

export interface HttpError {
  kind: string
  status?: number
  message?: string
}

export interface KeyPair {
  privateKey: string
  publicKey: string
}

export interface RecvDiag {
  drainCount: number
  queuedEvents: number
}

export interface SecurityContext {
  privateKey: string
  publicKey: string
  certificate: string
  certificateHash: string
}

export interface SendResult {
  sessionId: string
  success: boolean
  failedFiles: Array<string>
  error?: HttpError
}

export interface ServerHandle {
  fingerprint: string
  port: number
}

export interface ServerStatus {
  running: boolean
  activeSession?: string
  fingerprint?: string
}

export interface ShareLinkInfo {
  url: string
  port: number
  sessionId: string
}

export interface TransferFileInfo {
  fileId: string
  fileName: string
  size: number
  fileType: string
  preview?: string
  sha256?: string
}

export interface TransferRequest {
  sessionId: string
  senderAlias: string
  senderFingerprint: string
  senderProtocol: string
  files: Array<TransferFileInfo>
}

export declare function acceptTransfer(sessionId: string, fileIds: Array<string>): void

export declare function acceptWebDownload(sessionId: string): void

/** Cancel a hash operation by its cancel_id. */
export declare function cancelHash(cancelId: string): void

export declare function cancelLocalSession(sessionId: string): void

/** Cancel a CancellationToken by its id. */
export declare function cancelTokenCancel(id: string): void

export declare function cancelTransfer(sessionId: string): void

export declare function cancelTransferRemote(target: string, sessionId: string): Promise<void>

export declare function clientInfo(protocol: string, ip: string, port: number): Promise<string>

export declare function computeFingerprint(certPem: string): string

/**
  * Compute SHA-256 hash of a combined fingerprint string.
  * Returns the hex-encoded hash string (lowercase, 64 chars).
  * Used for verification page icon mapping.
  */
export declare function computeFingerprintHash(combined: string): string

/**
  * Create a CancellationToken and return its UUID id.
  * The token can be passed to hash_file_stream or upload_file for cancellation.
  */
export declare function createCancelToken(): string

/** Create a new RsCancellationToken instance. */
export declare function createCancellationToken(): RsCancellationToken

/** Factory function: create an RsHttpClient instance. */
export declare function createClientInstance(privateKey: string, cert: string, expectedFingerprint?: string | undefined | null, timeoutMs?: number | undefined | null, alias?: string | undefined | null, deviceType?: string | undefined | null, deviceModel?: string | undefined | null): RsHttpClient

export declare function createServer(config: string): Promise<ServerHandle>

export declare function createShareLink(files: string, alias: string): Promise<ShareLinkInfo>

export declare function declineTransfer(sessionId: string): void

export declare function declineWebDownload(sessionId: string): void

export declare function deinit(): void

export declare function discoveryAddDevice(device: string): Promise<void>

export declare function discoveryAnnounce(): Promise<void>

/**
  * Get device confirmation logs by fingerprint.
  * Returns a JSON array of log entries.
  */
export declare function discoveryDeviceLogs(fingerprint: string): string

export declare function discoveryDiscoverStaged(channels: string, interfaceIps: string, port: number, protocol: string, graceMs: number): Promise<void>

export declare function discoveryGetDevice(fingerprint: string): string

export declare function discoveryGetDevices(): string

export declare function discoveryMulticastError(): string

export declare function discoveryScanSubnet(interfaceIp: string, port: number, protocol: string): Promise<void>

export declare function discoverySetAnswerAnnouncements(answer: boolean): void

export declare function discoveryStop(): void

export declare function downloadFile(targetIp: string, port: number, protocol: string, sessionId: string, fileId: string, savePath: string, publicKey?: string | undefined | null): Promise<number>

/** Enable debug-level logging for the Rust layer. */
export declare function enableDebugLogging(): void

/** Mark a pending file download as failed (causes 500 response). */
export declare function failFileDownload(sessionId: string, fileId: string): void

/** Mark a pending file upload as failed (causes 500 response). */
export declare function failFileUpload(sessionId: string, fileId: string): void

/** Generate an Ed25519 key pair for device authentication tokens. */
export declare function generateKeyPair(): KeyPair

/**
  * Generate a full security context: RSA-2048 key pair, self-signed certificate,
  * and SHA-256 fingerprint. Used for TLS device identity.
  */
export declare function generateSecurityContext(): SecurityContext

export declare function getCurrentSendSessionId(): string

export declare function getFingerprint(): string

export declare function getLocalAddresses(): Array<string>

export declare function getLocalDevice(): string

/** Returns the native library name */
export declare function getNativeName(): string

/** Returns the native library version (from Cargo.toml) */
export declare function getNativeVersion(): string

/** Returns the LocalSend protocol version implemented by this library (e.g. "2.2") */
export declare function getProtocolVersion(): string

export declare function getRecvDiag(): RecvDiag

export declare function getServerStatus(): ServerStatus

/** Compute SHA-256 hash of an in-memory buffer (synchronous). */
export declare function hashBuffer(buffer: ArrayBuffer): string

/**
  * Compute the SHA-256 hash of a file at the given path.
  * Returns the hex-encoded hash string.
  */
export declare function hashFile(path: string): Promise<string>

/**
  * Compute the SHA-256 hash of a file with stream progress events.
  * Returns the cancel_id used for this operation.
  * Progress, completion, error, and cancellation events are pushed via EventCallback.
  */
export declare function hashFileStream(path: string, cancelId?: string | undefined | null): Promise<string>

/**
  * Compute the SHA-256 hash of a file with stream progress events.
  * Accepts an RsCancellationToken object for cancellation support.
  * Progress, completion, error, and cancellation events are pushed via EventCallback.
  */
export declare function hashFileStreamWithToken(path: string, cancelToken?: RsCancellationToken | undefined | null): Promise<string>

export declare function init(alias: string, deviceType: string, logLevel?: string | undefined | null): void

/** Whether `name` is a legal file name on the current platform. */
export declare function isValidFileName(name: string): boolean

export declare function pollDebugLog(): Array<string>

export declare function pollPendingRequests(): Array<TransferRequest>

export declare function prepareDownload(targetIp: string, port: number, protocol: string, sessionId?: string | undefined | null, pin?: string | undefined | null): Promise<string>

export declare function prepareSend(targetIp: string, port: number, protocol: string, filesJson: string, pin?: string | undefined | null, expectedFingerprint?: string | undefined | null, publicKey?: string | undefined | null): Promise<string>

/**
  * Read file timestamps (last modified, last accessed) as
  * RFC 3339 strings with nanosecond precision.
  */
export declare function readFileMetadata(path: string): FileMetadataResult | null

export declare function registerDevice(targetIp: string, targetPort: number, ourAlias: string, ourFingerprint: string, ourProtocol: string, ourDeviceModel: string | undefined | null, ourDeviceType: string | undefined | null, ourPort: number, ourIp?: string | undefined | null): Promise<string>

export declare function registerEventListener(callback: ((err: Error | null, arg: string) => any)): void

export declare function respondTransfer(sessionId: string, accept: boolean, acceptedFileIds: Array<string>): Promise<void>

/**
  * Rewrite `name` into a file name that is legal on the current platform,
  * replacing illegal characters with `_`.
  */
export declare function sanitizeFileName(name: string): string

export declare function sendFiles(target: string, senderAlias: string, files: string): Promise<SendResult>

/** Factory function: create an RsDiscovery instance. */
export declare function startDiscoveryInstance(configJson: string): Promise<RsDiscovery>

export declare function startDiscoveryV2(config: string): Promise<void>

export declare function startServer(port: number, useHttps: boolean, verifyChecksums: boolean, pin?: string | undefined | null): Promise<void>

/**
  * Factory function: create an RsHttpServer instance.
  *
  * This is the object-oriented alternative to the `start_server` free function.
  * The server instance holds its own state, independent of the global BridgeState.
  */
export declare function startServerInstance(port: number, useHttps: boolean, verifyChecksums: boolean, pin: string | undefined | null, alias: string, version: string | undefined | null, deviceModel: string | undefined | null, deviceType: string | undefined | null, fingerprint: string, showToken?: string | undefined | null, saveDir?: string | undefined | null, webSendFiles?: string | undefined | null, webPin?: string | undefined | null): Promise<RsHttpServer>

export declare function startWebUpload(): Promise<number>

export declare function stopServer(): void

export declare function stopShareServer(): Promise<void>

export declare function uploadFile(targetIp: string, port: number, protocol: string, sessionId: string, fileId: string, token: string, filePath: string, expectedFingerprint?: string | undefined | null, publicKey?: string | undefined | null, cancelId?: string | undefined | null): Promise<void>

export declare function uploadFromBuffer(targetIp: string, port: number, protocol: string, sessionId: string, fileId: string, token: string, buffer: ArrayBuffer, publicKey?: string | undefined | null, cancelId?: string | undefined | null): Promise<void>

/**
  * Verify that a PEM certificate matches an expected public key.
  * Used for trust-on-first-use (TOFU) security model.
  */
export declare function verifyCert(certPem: string, publicKey: string): void

export declare function verifyFingerprint(certPem: string, expected: string): boolean

/**
  * RsCancellationToken — object-oriented cancellation token.
  *
  * Replaces the old id-based cancel token system. Each token is a standalone
  * object that can be shared across multiple operations. Calling `cancel()`
  * triggers cancellation on all operations using this token.
  */
export declare class RsCancellationToken {
  /** Cancel the token. All operations using this token will be interrupted. */
  cancel(): void
  /** Check whether the token has been cancelled. */
  isCancelled(): boolean
}

export declare class RsHttpClient {
  /**
    * Prepare an upload to a remote device.
    * Returns JSON with sessionId and file tokens.
    */
  prepareUpload(protocol: string, ip: string, port: number, filesJson: string, publicKey?: string | undefined | null, pin?: string | undefined | null, cancelToken?: RsCancellationToken | undefined | null): Promise<string>
  /**
    * Register this device with a remote device.
    * Returns JSON with the remote device's info.
    */
  register(protocol: string, ip: string, port: number, payloadJson: string): Promise<string>
  /** Upload a file to a remote device. */
  upload(protocol: string, ip: string, port: number, sessionId: string, fileId: string, token: string, filePath: string, publicKey?: string | undefined | null, cancelToken?: RsCancellationToken | undefined | null): Promise<void>
  /** Cancel a remote transfer session. */
  cancel(protocol: string, ip: string, port: number, sessionId: string): Promise<void>
}

export declare class RsDiscovery {
  /** Send an announcement burst to the network. */
  announce(): Promise<void>
  /** Discover devices in stages: announce → probe known channels → wait grace period → fallback subnet scan. */
  discoverStaged(channels: string, interfaceIps: string, port: number, protocol: string, graceMs: number): Promise<void>
  /** Scan the /24 subnet of a specific interface. */
  scanSubnet(interfaceIp: string, port: number, protocol: string): Promise<void>
  /** Add a device confirmed outside of discovery into the store. */
  addDevice(deviceJson: string): Promise<void>
  /** Set whether to answer announcements of other devices. */
  setAnswerAnnouncements(answer: boolean): void
  /**
    * Get device confirmation logs by fingerprint.
    * Returns a JSON array of log entries.
    */
  deviceLogs(fingerprint: string): string
  /** Get the multicast error, if any. */
  multicastError(): string
  /** Stop discovery and release all sockets. */
  stop(): void
}

export declare class RsHttpServer {
  /**
    * Respond to a prepare-upload request by accepting specific file IDs.
    * Pass an empty or None list to decline the entire request.
    */
  respondPrepareUpload(acceptedFileIds?: Array<string> | undefined | null): void
  /** Respond to a prepare-upload request for a specific session by accepting specific file IDs. */
  respondPrepareUploadSession(sessionId: string, acceptedFileIds?: Array<string> | undefined | null): void
  /**
    * Respond to a file-upload request by providing a save path.
    * In auto-save mode (default), the event loop already sends FileUploadTarget::Path
    * to target_tx, so this method is for the manual/advanced path where the caller
    * wants to override the save location.
    */
  respondFileUpload(sessionId: string, fileId: string, filePath: string, fileSize: number): void
  /** Respond to a web prepare-download request (accept or decline). */
  respondPrepareDownload(sessionId: string, accept: boolean): void
  /** Respond to a web file-download request by providing file content path. */
  respondFileDownload(sessionId: string, fileId: string, filePath: string): void
  /** Mark a pending file download as failed (causes 500 response). */
  failFileDownload(sessionId: string, fileId: string): void
  /** Mark a pending file upload as failed (causes 500 response). */
  failFileUpload(sessionId: string, fileId: string): void
  /** Cancel a session by session ID. Also notifies the remote peer via HTTP cancel. */
  cancelSession(sessionId: string): void
  /** Stop the HTTP server and release the port. */
  stop(): void
}

