/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface FileMetadataResult {
  lastModified?: string
  lastAccessed?: string
}

export interface KeyPair {
  privateKey: string
  publicKey: string
}

export interface ProgressInfo {
  sessionId: string
  fileId: string
  bytesSent: number
  totalBytes: number
  filePath: string
}

export interface RecvDiag {
  drainCount: number
  queuedEvents: number
}

export interface SecurityContext {
  privateKey: string
  publicKey: string
  certificate: string
  certificateHash: string
}

export interface SendResult {
  sessionId: string
  success: boolean
  failedFiles: Array<string>
}

export interface ServerHandle {
  fingerprint: string
  port: number
}

export interface ServerStatus {
  running: boolean
  activeSession?: string
  fingerprint?: string
}

export interface ShareLinkInfo {
  url: string
  port: number
  sessionId: string
}

export interface TransferFileInfo {
  fileId: string
  fileName: string
  size: number
  fileType: string
  preview?: string
  sha256?: string
}

export interface TransferRequest {
  sessionId: string
  senderAlias: string
  senderFingerprint: string
  senderProtocol: string
  files: Array<TransferFileInfo>
}

export declare function acceptTransfer(sessionId: string, fileIds: Array<string>): void

export declare function cancelLocalSession(sessionId: string): void

export declare function cancelTransfer(sessionId: string): void

export declare function cancelTransferRemote(target: string, sessionId: string): Promise<void>

export declare function computeFingerprint(certPem: string): string

/**
  * Compute SHA-256 hash of a combined fingerprint string.
  * Returns the hex-encoded hash string (lowercase, 64 chars).
  * Used for verification page icon mapping.
  */
export declare function computeFingerprintHash(combined: string): string

export declare function createServer(config: string): Promise<ServerHandle>

export declare function createShareLink(files: string, alias: string): Promise<ShareLinkInfo>

export declare function declineTransfer(sessionId: string): void

export declare function deinit(): void

/** Generate an Ed25519 key pair for device authentication tokens. */
export declare function generateKeyPair(): KeyPair

/**
  * Generate a full security context: RSA-2048 key pair, self-signed certificate,
  * and SHA-256 fingerprint. Used for TLS device identity.
  */
export declare function generateSecurityContext(): SecurityContext

export declare function getCurrentSendSessionId(): string

export declare function getDevicesJson(): string

export declare function getFingerprint(): string

export declare function getLocalAddresses(): Array<string>

export declare function getLocalDevice(): string

/** Returns the native library name */
export declare function getNativeName(): string

/** Returns the native library version (from Cargo.toml) */
export declare function getNativeVersion(): string

/** Returns the LocalSend protocol version implemented by this library (e.g. "2.2") */
export declare function getProtocolVersion(): string

export declare function getRecvDiag(): RecvDiag

export declare function getServerStatus(): ServerStatus

/**
  * Compute the SHA-256 hash of a file at the given path.
  * Returns the hex-encoded hash string.
  */
export declare function hashFile(path: string): Promise<string>

export declare function init(alias: string, deviceType: string, logLevel?: string | undefined | null): void

/** Whether `name` is a legal file name on the current platform. */
export declare function isValidFileName(name: string): boolean

export declare function pollDebugLog(): Array<string>

export declare function pollPendingRequests(): Array<TransferRequest>

export declare function pollProgress(): Array<ProgressInfo>

export declare function pollSendProgress(): Array<ProgressInfo>

export declare function pollShareProgress(): Array<ProgressInfo>

export declare function prepareSend(targetIp: string, port: number, protocol: string, filesJson: string, pin?: string | undefined | null, expectedFingerprint?: string | undefined | null): Promise<string>

/**
  * Read file timestamps (last modified, last accessed) as
  * RFC 3339 strings with nanosecond precision.
  */
export declare function readFileMetadata(path: string): FileMetadataResult | null

/**
  * Register this device with a remote device via HTTP/HTTPS with mTLS support.
  *
  * Unlike the ArkTS HTTP client, this function uses the Rust LsHttpClient which
  * carries client certificates for proper mTLS handshakes. This is essential for
  * registering with HTTPS-only servers.
  *
  * Tries `our_protocol` first, then the alternative. Returns remote device info on success.
  */
export declare function registerDevice(targetIp: string, targetPort: number, ourAlias: string, ourFingerprint: string, ourProtocol: string, ourDeviceModel: string | undefined | null, ourDeviceType: string | undefined | null, ourPort: number, ourIp?: string | undefined | null): Promise<string>

export declare function registerEventListener(callback: ((err: Error | null, arg: string) => any)): void

export declare function respondTransfer(sessionId: string, accept: boolean, acceptedFileIds: Array<string>): Promise<void>

/**
  * Rewrite `name` into a file name that is legal on the current platform,
  * replacing illegal characters with `_`.
  */
export declare function sanitizeFileName(name: string): string

export declare function sendFiles(target: string, senderAlias: string, files: string): Promise<SendResult>

export declare function startDiscovery(port: number): Promise<void>

export declare function startServer(port: number, useHttps: boolean, verifyChecksums: boolean, pin?: string | undefined | null): Promise<void>

export declare function stopDiscovery(): void

export declare function stopServer(): void

export declare function stopShareServer(): void

export declare function uploadFile(targetIp: string, port: number, protocol: string, sessionId: string, fileId: string, token: string, filePath: string, expectedFingerprint?: string | undefined | null): Promise<void>

/**
  * Verify that a PEM certificate matches an expected public key.
  * Used for trust-on-first-use (TOFU) security model.
  */
export declare function verifyCert(certPem: string, publicKey: string): void

export declare function verifyFingerprint(certPem: string, expected: string): boolean

